version: '3.9'
services:
  db:
    image: postgres:16
    container_name: bank-db
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bankdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bank-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create 
      SPRING_SQL_INIT_MODE: always         
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true  # И эту
    ports:
      - "8080:8080"

volumes:
  pgdata: